from collections.abc import Sequence
from typing import Protocol

from library_api.catalog.domain.entities import Author, Book


class AuthorRepository(Protocol):
    async def get(self, id_: int) -> Author | None: ...
    async def list(self, *, offset: int = 0, limit: int = 100) -> Sequence[Author]: ...
    async def add(self, author: Author) -> Author: ...
    async def update(self, author: Author) -> Author: ...
    async def delete(self, author: Author) -> None: ...


class BookRepository(Protocol):
    async def get(self, id_: int) -> Book | None: ...
    async def get_by_isbn(self, isbn: str) -> Book | None: ...
    async def list(self, *, offset: int = 0, limit: int = 100) -> Sequence[Book]: ...
    async def add(self, book: Book) -> Book: ...
    async def update(self, book: Book) -> Book: ...
    async def delete(self, book: Book) -> None: ...
