from collections.abc import Sequence
from typing import Protocol

from library_api.lending.domain.entities import Loan, Member


class MemberRepository(Protocol):
    async def get(self, id_: int) -> Member | None: ...
    async def get_by_email(self, email: str) -> Member | None: ...
    async def list(self, *, offset: int = 0, limit: int = 100) -> Sequence[Member]: ...
    async def add(self, member: Member) -> Member: ...
    async def update(self, member: Member) -> Member: ...
    async def delete(self, member: Member) -> None: ...


class LoanRepository(Protocol):
    async def get(self, id_: int) -> Loan | None: ...
    async def list(self, *, offset: int = 0, limit: int = 100) -> Sequence[Loan]: ...
    async def add(self, loan: Loan) -> Loan: ...
    async def update(self, loan: Loan) -> Loan: ...
